import { getAllSettings } from './settingsService';

export const sendEmail = async (payload: { to: string; cc?: string; subject: string; body: string; attachments?: any[] }) => {
  try {
    const response = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    const result = await response.json();
    
    if (!result.success) {
      // Log failure to admin
      await fetch('/api/logs/admin', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: `Email sending failed to ${payload.to}: ${result.error}` })
      });
      throw new Error(result.error);
    }
    
    return result;
  } catch (err: any) {
    console.error("Email service error:", err);
    throw err;
  }
};

const getConfidenceLabel = (score: number) => {
  if (score >= 80) return "High";
  if (score >= 60) return "Moderate";
  return "Requires Review";
};

export const sendPrescriptionEmail = async (patient: any, session: any, prescriptions: any[]) => {
  const settings = await getAllSettings();
  const clinicName = settings.clinic_name || "H.E.A.L.E.R Clinic";
  const doctorEmail = settings.doctor_email;

  const body = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
      <h2 style="color: #2563eb; text-align: center;">${clinicName} - Prescription Report</h2>
      <hr />
      <p><strong>Patient Name:</strong> ${patient.name}</p>
      <p><strong>Age / Gender:</strong> ${patient.age} / ${patient.gender}</p>
      <p><strong>Date / Time:</strong> ${new Date(session.timestamp).toLocaleString()}</p>
      <hr />
      <h3>Diagnosis</h3>
      <p><strong>Identified Condition:</strong> ${session.diagnosed_disease}</p>
      <p><strong>Confidence:</strong> ${getConfidenceLabel(session.confidence_score)}</p>
      <hr />
      <h3>Prescribed Medicines</h3>
      <table style="width: 100%; border-collapse: collapse;">
        <thead>
          <tr style="background-color: #f8fafc;">
            <th style="border: 1px solid #e2e8f0; padding: 8px; text-align: left;">Medicine</th>
            <th style="border: 1px solid #e2e8f0; padding: 8px; text-align: left;">Dosage</th>
            <th style="border: 1px solid #e2e8f0; padding: 8px; text-align: left;">Frequency</th>
            <th style="border: 1px solid #e2e8f0; padding: 8px; text-align: left;">Duration</th>
          </tr>
        </thead>
        <tbody>
          ${prescriptions.map(p => `
            <tr>
              <td style="border: 1px solid #e2e8f0; padding: 8px;">${p.medicine_name}</td>
              <td style="border: 1px solid #e2e8f0; padding: 8px;">${p.dosage}</td>
              <td style="border: 1px solid #e2e8f0; padding: 8px;">${p.frequency}</td>
              <td style="border: 1px solid #e2e8f0; padding: 8px;">${p.duration}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      <p style="margin-top: 30px; font-size: 0.8em; color: #64748b; text-align: center;">
        This report was generated by H.E.A.L.E.R. Please consult a doctor for further advice.
      </p>
    </div>
  `;

  return sendEmail({
    to: patient.email,
    cc: doctorEmail,
    subject: `H.E.A.L.E.R Prescription Report - ${patient.name} - ${new Date().toLocaleDateString()}`,
    body
  });
};

export const sendQRCodeEmail = async (patient: any, qrCodeBase64: string) => {
  const body = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px;">
      <h2 style="color: #2563eb;">Your H.E.A.L.E.R Patient QR Code</h2>
      <p>Dear ${patient.name},</p>
      <p>Please find your QR code attached. You can use this for future visits to our clinic to quickly retrieve your medical history.</p>
      <p>Best regards,<br>H.E.A.L.E.R Team</p>
    </div>
  `;

  // Attach qr code
  const attachments = [
    {
      filename: 'patient-qr-code.png',
      content: qrCodeBase64.split("base64,")[1],
      encoding: 'base64'
    }
  ];

  return sendEmail({
    to: patient.email,
    subject: "Your H.E.A.L.E.R Patient QR Code",
    body,
    attachments
  });
};

export const sendAutoReferralEmail = async (patient: any, session: any, prescriptions: any[]) => {
  const settings = await getAllSettings();
  const doctorEmail = settings.doctor_email;

  const body = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 2px solid #ef4444; padding: 20px; border-radius: 10px;">
      <h2 style="color: #ef4444; text-align: center;">URGENT: Auto-Referral</h2>
      <hr />
      <p>A patient has been identified with a serious condition requiring immediate attention.</p>
      <p><strong>Patient Name:</strong> ${patient.name}</p>
      <p><strong>Identified Condition:</strong> ${session.diagnosed_disease}</p>
      <hr />
      <h3>Full Session Details</h3>
      <p><strong>Age / Gender:</strong> ${patient.age} / ${patient.gender}</p>
      <p><strong>Timestamp:</strong> ${new Date(session.timestamp).toLocaleString()}</p>
      <p><strong>Prescribed Action:</strong> ${session.action_taken}</p>
      <hr />
      <h3>Initial Prescription</h3>
      <ul>
        ${prescriptions.map(p => `<li>${p.medicine_name} (${p.dosage}, ${p.frequency}, ${p.duration})</li>`).join('')}
      </ul>
    </div>
  `;

  return sendEmail({
    to: doctorEmail,
    subject: `URGENT: Auto-Referral - ${patient.name} - ${session.diagnosed_disease}`,
    body
  });
};
